# Generated by Django 4.1.2 on 2023-05-18 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('imagen', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.TextField()),
                ('nombre', models.TextField()),
                ('apellido1', models.TextField()),
                ('apellido2', models.TextField()),
                ('token_sesion', models.TextField(default=None, null=True)),
                ('token_recuperacion', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contraseñas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraseña', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('usuario', models.TextField(null=True)),
                ('fecha', models.DateField()),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locked_and_secure_app.grupos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locked_and_secure_app.usuarios')),
            ],
        ),
    ]
