# Generated by Django 4.1.2 on 2023-06-05 20:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locked_and_secure_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contraseñas',
            name='plataforma',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='grupos',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locked_and_secure_app.usuarios'),
        ),
        migrations.AlterField(
            model_name='contraseñas',
            name='contraseña',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='contraseñas',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contraseñas',
            name='id_grupo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locked_and_secure_app.grupos'),
        ),
        migrations.AlterField(
            model_name='contraseñas',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locked_and_secure_app.usuarios'),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='imagen',
            field=models.TextField(default=None, null=True),
        ),
    ]
