# Generated by Django 4.1.2 on 2023-05-21 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locked_and_secure_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='clave',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contraseñas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 5, 21, 10, 57, 18, 838533)),
        ),
    ]
