# Generated by Django 4.1.7 on 2023-05-31 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locked_and_secure_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locked_and_secure_app.usuarios'),
        ),
        migrations.AlterField(
            model_name='contraseñas',
            name='id_grupo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locked_and_secure_app.grupos'),
        ),
        migrations.AlterField(
            model_name='contraseñas',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locked_and_secure_app.usuarios'),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='imagen',
            field=models.TextField(default=None, null=True),
        ),
    ]
