# Generated by Django 4.1.2 on 2023-05-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locked_and_secure_app', '0002_grupos_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraseñas',
            name='id_grupo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locked_and_secure_app.grupos'),
        ),
        migrations.AlterField(
            model_name='contraseñas',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locked_and_secure_app.usuarios'),
        ),
    ]
