# Generated by Django 4.1.2 on 2023-06-01 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locked_and_secure_app', '0003_alter_contraseñas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraseñas',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
