# Generated by Django 4.1.7 on 2023-05-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locked_and_secure_app', '0004_alter_contraseñas_id_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='imagen',
            field=models.TextField(default=None, null=True),
        ),
    ]
