# Generated by Django 4.1.2 on 2023-06-03 21:52

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locked_and_secure_app', '0004_alter_contraseñas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='clave',
            field=fernet_fields.fields.EncryptedTextField(default=None),
            preserve_default=False,
        ),
    ]
