# Generated by Django 4.1.2 on 2023-06-03 21:53

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locked_and_secure_app', '0005_alter_usuarios_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='clave',
        ),
        migrations.AlterField(
            model_name='contraseñas',
            name='contraseña',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
