# Generated by Django 4.1.2 on 2023-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locked_and_secure_app', '0006_remove_usuarios_clave_alter_contraseñas_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='contraseñas',
            name='plataforma',
            field=models.TextField(null=True),
        ),
    ]
